
import {responsiveFontSize,} from 'react-native-responsive-dimensions';
const fontFamily = {
  RobotoLight:'Roboto-Light',
  RobotoRegular:'Roboto-Regular',
  RobotoMedium:'Roboto-Medium',
  RobotoBold:'Roboto-Bold',
  PoppinsRegular:'Poppins-Regular',
  PoppinsMedium:'Poppins-Medium',
  PoppinsLight:'Poppins-Light',
  MonstserratMedium:'Montserrat-Medium',
  MonstserratRegular:'Montserrat-Regular',
  TangerineBold:'Tangerine-Bold',
  BalooBhaijaan:'BalooBhaijaan2-ExtraBold',
  BalooBhaijaanBold:'BalooBhaijaan2-Bold',
  BalooBhaijaanRegular:'BalooBhaijaan2-Regular',
  BalooBhaijaan2Medium:'BalooBhaijaan2-Medium',
  SatoshiVariable:'Satoshi-Variable',
  SatoshiLight:'Satoshi-Light',
  SatoshiMedium:'Satoshi-Medium',
  SatoshiRegular:'Satoshi-Regular',
  SatoshiLight:'Satoshi-Light',
  SatoshiBold:'Satoshi-Bold',
}
const fontSize = {
 h1:responsiveFontSize(1.4),
 h2:responsiveFontSize(1.5),
 h3:responsiveFontSize(7),
 h4:responsiveFontSize(3.4),
 h5:responsiveFontSize(1.9),
 h6:responsiveFontSize(2),
 h7:responsiveFontSize(2.5),
 h8:responsiveFontSize(3.5),
 h9:responsiveFontSize(4),
 h10:responsiveFontSize(1.7),
 h11:responsiveFontSize(10),
 h12:responsiveFontSize(12),
 h13:responsiveFontSize(1),
 h14:responsiveFontSize(1.3),
 h15:responsiveFontSize(3),
 h16:responsiveFontSize(2.3),
}
export  {fontSize ,fontFamily}
