import { StyleSheet } from 'react-native';
import { fontSize, fontFamily } from '../fonts';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
import { scale } from 'react-native-size-matters';
import { colors } from '../color';
export const appStyles = StyleSheet.create({
  Splash: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  splashlogo: {
    width: scale(300),
    height: scale(190),
    resizeMode: 'contain',
    opacity: 1,
  },
  splashview: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',

  },

  imageBackground: {
    flex: 1,
    width: responsiveWidth(101),

  },
  container1: {
    flex: 1,
    backgroundColor: colors.color7,
  },
  Splashcontainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  maskview: {
    height: responsiveHeight(20),
    width: responsiveWidth(100),
  },
  chatback: {
    width: responsiveWidth(7),
    height: responsiveHeight(7),
    resizeMode: 'contain',
    marginRight: -responsiveWidth(15),
  },
  headerText: {
    color: colors.color1,
    alignItems: 'center',
    marginLeft: responsiveWidth(20),
    fontSize: fontSize.h6,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    opacity: 1,
  },
  headerContainer: {
    width: responsiveWidth(100),
    height: responsiveHeight(7),
    backgroundColor: colors.color7,
    borderWidth: 1,
    borderColor: colors.color11,
    alignItems: 'center',
    flexDirection: 'row',
    paddingLeft: 23,
  },
  arrow: {
    width: scale(29),
    height: scale(29),
    alignSelf: 'flex-start',
    resizeMode: 'contain',
    opacity: 1,
  },
  swantext: {
    fontFamily: fontFamily.BalooBhaijaan,
    fontSize: fontSize.h3,
    alignSelf: 'center',
    marginTop: responsiveHeight(6),
    opacity: 1,
  },
  // swantxt: {
  //   color: colors.color7,
  //   alignSelf: 'center',
  //   fontFamily: fontFamily.BalooBhaijaan,
  //   fontSize: fontSize.h3,
  //   marginBottom: responsiveHeight(24),
  //   opacity: 1,
  // },
  logo: {
    width: scale(218),
    height: scale(160),
    alignSelf: 'center',
    resizeMode: 'contain',
    marginTop: responsiveHeight(6)
  },
  // gradientview: {
  //   width: responsiveWidth(100),
  //   height: responsiveHeight(8),
  //   marginTop: responsiveHeight(6),
  //   marginLeft: responsiveWidth(33),
  // },
  logoview: {
    width: responsiveWidth(100),
    height: responsiveHeight(5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo1: {
    width: scale(100),
    height: scale(100),
    alignSelf: 'center',
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  userpic: {
    width: scale(25),
    height: scale(25),
    alignSelf: 'center',
    alignSelf: 'flex-end',
    marginTop: -responsiveHeight(8),
    marginRight: responsiveWidth(4),
    resizeMode: 'contain',
    opacity: 1,
  },
  cardview: {
    flexDirection: 'column',
    backgroundColor: colors.color7,
    padding: responsiveWidth(3),
    borderRadius: responsiveWidth(6),
    borderColor: colors.color30,
    borderWidth: 1,
    width: scale(153),
    height: scale(173),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: responsiveWidth(4),
  },
  titleStyle: {
    color: colors.color28,
    fontFamily: fontFamily.SatoshiLight,
    fontWeight: '400',
    marginTop: responsiveHeight(1.5),
    opacity: 1,
  },
  imagestayle: {
    width: scale(115),
    height: scale(115),
    alignSelf: 'center',
    borderRadius: responsiveWidth(100),
    marginTop: responsiveHeight(3.5),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(4),
    opacity: 1,
  },
  descriptionStyle: {
    color: colors.color7,
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h2,
    fontWeight: '400',
    opacity: 1,
  },
  notificationtxt: {
    color: colors.color10,
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h2,
    fontWeight: '700',
    marginTop: responsiveHeight(6),
    marginLeft: responsiveWidth(4.6),
    marginBottom: responsiveHeight(0.3),
    opacity: 1,
  },
  // Monthlyview: {
  //   flexDirection: 'row',
  //   justifyContent: 'flex-start',
  //   alignItems: 'center',
  //   marginTop: responsiveHeight(4),
  // },
  // Monthly: {
  //   color: colors.color10,
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h2,
  //   fontWeight: '700',
  //   marginLeft: responsiveWidth(4),
  //   marginRight: responsiveWidth(4),
  // },
  // yearly: {
  //   color: colors.color10,
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h2,
  //   fontWeight: '700',
  //   marginRight: -responsiveWidth(35),
  // },
  // purchasingview: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   height: scale(150),
  //   borderRadius: responsiveWidth(5),
  //   backgroundColor: colors.color7,
  //   borderWidth: 0.5,
  //   borderColor: colors.color10,
  //   marginTop: responsiveHeight(3),
  // },
  // cancle: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   height: scale(48),
  //   borderRadius: responsiveWidth(5),
  //   backgroundColor: colors.color7,
  //   borderWidth: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderColor: colors.color20,
  //   marginTop: responsiveHeight(3),
  // },
  // cancletxt: {
  //   color: colors.color20,
  //   fontFamily: fontFamily.SatoshiVariable,
  //   fontSize: fontSize.h6,
  //   fontWeight: '700',
  // },
  // plantxt: {
  //   color: colors.color4,
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h2,
  //   marginLeft: responsiveWidth(3.5),
  //   fontWeight: '700',
  //   marginTop: responsiveHeight(1.5),
  //   opacity: 1,
  // },
  // dllortext: {
  //   color: colors.color10,
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h8,
  //   marginLeft: responsiveWidth(74),
  //   fontWeight: '700',
  //   marginTop: -responsiveHeight(9),
  // },
  // personalitytxt: {
  //   color: colors.color10,
  //   lineHeight: scale(20),
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h2,
  //   marginLeft: responsiveWidth(4.5),
  //   fontWeight: '400',
  //   marginTop: responsiveHeight(2),
  // },
  // switchbottomview: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   height: scale(48),
  //   borderBottomLeftRadius: responsiveWidth(5),
  //   borderBottomRightRadius: responsiveWidth(5),
  //   backgroundColor: colors.color16,
  //   borderWidth: 1,
  //   borderColor: colors.color30,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // switchmiddleview: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   height: scale(48),
  //   backgroundColor: colors.color16,
  //   borderWidth: 1,
  //   borderColor: colors.color30,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // switchview: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   height: scale(48),
  //   borderTopLeftRadius: responsiveWidth(5),
  //   borderTopRightRadius: responsiveWidth(5),
  //   backgroundColor: colors.color16,
  //   borderWidth: 1,
  //   borderColor: colors.color30,
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // swithtxt: {
  //   color: colors.color4,
  //   fontFamily: fontFamily.SatoshiVariable,
  //   fontSize: fontSize.h2,
  //   marginRight: responsiveWidth(45),
  //   fontWeight: '700',
  // },
  // swithtxt1: {
  //   color: colors.color4,
  //   fontFamily: fontFamily.SatoshiVariable,
  //   fontSize: fontSize.h2,
  //   marginRight: responsiveWidth(42),
  //   fontWeight: '700',
  // },
  // addStyle: {
  //   color: colors.color7,
  //   alignSelf: 'center',
  //   fontFamily: fontFamily.SatoshiVariable,
  //   fontSize: fontSize.h14,
  //   fontWeight: '400',
  // },
  Pluscircleimage: {
    width: scale(58),
    height: scale(58),
    alignSelf: 'center',
    borderRadius: responsiveWidth(100),
    marginTop: responsiveHeight(2),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(4),
  },
  Accounttxt: {
    color: colors.color28,
    fontFamily: fontFamily.SatoshiMedium,
    fontWeight: '400',
    fontSize: fontSize.h4,
    alignSelf: 'center',
    marginTop: responsiveHeight(4),
  },
  scrollViewContainer: {
    flexGrow: 1,
  },
  uploadimage: {
    width: scale(18),
    height: scale(18),
    resizeMode: 'contain',
    marginRight: responsiveWidth(4),
  },
  Nullimage: {
    width: scale(100),
    height: scale(100),
    alignSelf: 'center',
    resizeMode: 'contain',
    marginTop: responsiveHeight(3),
  },

  JohnDoe: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiMedium,
    fontSize: fontSize.h15,
    fontWeight: '400',
    marginTop: responsiveHeight(2),
  },
  buttonview: {
    flexDirection: 'row',

    backgroundColor: colors.color34,
    borderRadius: responsiveWidth(50),
    width: scale(260),
    height: scale(48),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  subsciption: {
    color: colors.color4,
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h10,
    // marginRight: responsiveWidth(30),
    marginLeft: responsiveWidth(2.5),
    opacity: 1,
    fontWeight: '700',
  },
  follow: {
    color: colors.color4,
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h10,
    marginLeft: responsiveWidth(2),
    opacity: 1,
    fontWeight: '700'
  },
  frame1: {
    width: scale(70),
    height: scale(24),
    resizeMode: 'contain',

  },
  facebookview: {
    flexDirection: 'row',
    marginLeft: responsiveWidth(29),
    gap: 6
  },
  Setting: {
    width: scale(24),
    height: scale(24),
    resizeMode: 'contain',

  },
  drawerStyle: {
    backgroundColor: 'transparent',
    borderBottomRightRadius: 35,
    borderTopRightRadius: 35,
    width: 90,
  },
  johndoetxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiLight,
    fontSize: fontSize.h6,
    fontWeight: '400',
    marginTop: responsiveHeight(1),
  },
  swantxt1: {
    width: scale(60),
    height: scale(60),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(28),
  },
  frame: {
    width: scale(144),
    height: scale(144),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
  },
  disclaimertxt: {
    color: colors.color9,
    textAlign: 'justify',
    lineHeight: responsiveHeight(2),
    justifyContent: 'space-evenly',
    fontFamily: fontFamily.SatoshiLight,
    fontWeight: '600',
    fontSize: fontSize.h2,
    padding: responsiveWidth(5),
    opacity: 1,
  },
  Entertxt: {
    color: colors.color28,
    fontFamily: fontFamily.SatoshiLight,
    fontWeight: '500',
    alignSelf: 'center',
    fontSize: fontSize.h5,
    marginRight:responsiveWidth(2),
    opacity: 1,
  },
  input: {
    height: responsiveHeight(6.5),
    width: responsiveWidth(75),
  },
  circleview: {
    width: scale(150),
    height: scale(150),
    borderRadius: responsiveWidth(100),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },

  upload: {
    width: scale(24),
    height: scale(24),
    resizeMode: 'center',
  },
  uploadtxt: {
    color: colors.color7,
    fontFamily: fontFamily.SatoshiMedium,
    fontSize: fontSize.h2,
  },
  horizontalLine: {
    borderBottomColor: colors.color30,
    borderBottomWidth: 1,
    width: scale(170),
    height: scale(1),
    alignSelf: 'center',
  },
  TermsText: {
    color: colors.color10,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    fontSize: fontSize.h2,
    marginLeft: responsiveWidth(1),
    textDecorationColor:colors.color4,
    textDecorationStyle:'solid',
    textDecorationLine:'underline'
  },
  ResetLocktxt1: {
    alignSelf: 'center',
    color: colors.color9,
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiMedium,
    fontWeight: '400',
    marginTop: -responsiveHeight(5),
    opacity: 1,
  },
  ResetLocktxt2: {
    alignSelf: 'center',
    color: colors.color9,
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiMedium,
    fontWeight: '400',
    opacity: 1,
  },
  ResetLock: {
    height: responsiveHeight(40),
    width: responsiveWidth(40),
    alignSelf: 'center',
    resizeMode: 'contain',
    opacity: 1,
    marginTop: -responsiveHeight(6.5),
  },
  rowContainer: {
    flexDirection: 'row',
    marginTop: responsiveHeight(7),
    width: responsiveWidth(90),
    height: responsiveHeight(8),
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  Accept: {
    fontSize: fontSize.h2,
    color: colors.color10,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
  },
  acceptview: {
    flexDirection: 'row',
    marginTop: responsiveHeight(7),
    width: responsiveWidth(90),
    height: responsiveHeight(6.5),
    alignSelf: 'center',
  },

  rememberMeText: {
    fontSize: fontSize.h2,
    color: colors.color10,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    marginRight: responsiveWidth(30),
    alignSelf: 'flex-start',
  },
  forgotPasswordText: {
    color: colors.color10,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    fontSize: fontSize.h2,
    alignSelf: 'flex-end',
  },
  plancontainer: {
    width: scale(320),
    alignSelf: 'center',
    height: scale(150),
    borderRadius: responsiveWidth(5),
  },
  circle: {
    width: scale(70),
    height: scale(24),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(73),
    marginTop: -responsiveHeight(2.8),
  },
  purchasinggrview: {
    width: scale(320),
    alignSelf: 'center',
    height: scale(150),
    borderRadius: responsiveWidth(5),
    backgroundColor: colors,
    marginTop: responsiveHeight(3),
  },
  Lubemeupcontainer: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(220),
    backgroundColor: colors.color33,
    height: scale(49),
    borderRadius: responsiveWidth(50),
  },
  Lubemeuptext: {
    color: colors.color7,
    fontSize: fontSize.h6,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700'
  },
  user: {
    width: scale(18),
    height: scale(18),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(3),
  },
  AccountView: {
    flexDirection: 'row',
    marginTop: responsiveHeight(2),
    backgroundColor: colors.color16,
    width: scale(220),
    height: scale(48),
    borderRadius: responsiveWidth(50),
    justifyContent: 'center',
    alignItems: 'center',
  },
  yestxt: {
    color: colors.color7,
    marginLeft: responsiveWidth(2),
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h6,
  },
  notxt: {
    color: colors.color4,
    marginLeft: responsiveWidth(2),
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h6,
  },
  loginbottomview: {
    height: responsiveHeight(10),
    width: responsiveWidth(100),
    alignItems: 'center',
    marginTop: responsiveHeight(3),
  },
  // DontAccounttxt: {
  //   color: colors.color9,
  //   fontFamily: fontFamily.SatoshiLight,
  //   fontSize: fontSize.h2,
  //   marginTop: responsiveHeight(2),
  // },
  image: {
    height: responsiveHeight(4),
    width: responsiveWidth(4),
    resizeMode: 'contain',
  },
  checkboxContainer: {
    position: 'relative',
  },
  overlay: {
    width: scale(20),
    height: scale(20),
    borderRadius: responsiveWidth(1),
    marginTop: -responsiveHeight(0.2),
    position: 'absolute',
  },
  checkbox: {
    width: scale(20),
    height: scale(20),
    alignSelf: 'flex-start',
    marginRight: responsiveWidth(2),
    borderRadius: responsiveWidth(1),
    marginTop: -responsiveHeight(0.2),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  imagedisaster:{
    width: scale(30),
    height: scale(30),
    resizeMode: 'contain',

  },
  locationtag: {
    width: scale(24),
    height: scale(24),
    resizeMode: 'contain',
    // marginTop: -responsiveHeight(7.2),
    // marginLeft: responsiveWidth(82.5)
  },
  imagetick: {
    height: responsiveHeight(4),
    width: responsiveWidth(4),
    resizeMode: 'contain',
  },
  Btnarrow: {
    width: scale(20),
    height: scale(20),
    marginRight: responsiveWidth(1.5),
    resizeMode: 'contain',
  },
  // codeInputField: {
  //   width: scale(40), // Adjust the width of each OTP input field
  //   height: scale(48), // Adjust the height of each OTP input field
  //   borderWidth: 0.5,
  //   borderRadius: responsiveWidth(4.3),
  //   borderColor: colors.color10, // Customize the border color
  //   color: colors.color10, // Customize the text color
  //   fontSize: responsiveFontSize(1.5), // Customize the text size
  //   marginHorizontal: responsiveWidth(1.7), // Adjust the horizontal margin between OTP input fields
  // },
  // otpview: {
  //   width: responsiveWidth(90),
  //   height: responsiveHeight(7),
  //   marginTop: responsiveHeight(4.5),
  //   alignSelf: 'center',
  // },
  // otpmainview: {
  //   width: '100%',
  //   height: responsiveHeight(7),
  //   alignSelf: 'center',
  // },
  CAtxt: {
    color: colors.color4,
    marginLeft: responsiveWidth(2),
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h6,
    fontWeight: '700'
  },

  inputView: {
    height: responsiveHeight(6),
    width: responsiveWidth(90),
    borderRadius: responsiveWidth(3.3),
    borderColor: colors.color10,
    borderWidth: 0.5,
    alignSelf: 'center',
    flexDirection: 'row',
    backgroundColor: colors.color7,
    alignItems: 'center',
    marginTop: responsiveHeight(1),
  },
  inputmainview: {
    height: responsiveHeight(6),
    width: responsiveWidth(90),
    alignSelf: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: colors.color7,
  },
  eye: {
    width: scale(15),
    height: scale(15),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(65.5)
  },
  Email: {
    width: scale(18),
    height: scale(18),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(3),
  },
  search: {
    width: scale(18),
    height: scale(18),
    resizeMode: 'contain',
    marginRight: responsiveWidth(30),
  },
  uploadfile: {
    color: colors.color29,
    marginLeft: responsiveWidth(2)
  },
  label: {
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    color: colors.color10,
    textAlign: 'left',
    marginBottom: -responsiveHeight(0.2),
  },
  // entertxt: {
  //   color: colors.color9,
  //   alignSelf: 'center',
  //   marginTop: responsiveHeight(4),
  //   fontFamily: fontFamily.SatoshiMedium,
  //   fontWeight: '100',
  // },
  packetimage: {
    width: scale(150),
    height: scale(150),
    resizeMode: 'contain',
    marginTop: responsiveHeight(8),
    alignSelf: 'center',
  },
  Onboarding: {
    color: colors.color1,
    alignItems: 'center',
    marginLeft: responsiveWidth(25),
    fontSize: fontSize.h6,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
  },
  verifytxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiMedium,
    fontWeight: '400',
    fontSize: fontSize.h15,
    marginTop: responsiveHeight(3.5),
  },
  senttxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiRegular,
    marginTop: responsiveHeight(1.5),
    opacity: 1,
  },
  emailtxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiRegular,
    fontWeight: '700',
  },
  buttoninput: {
    flexDirection: 'row',
    width: scale(350),
    height: scale(48),
    marginTop: responsiveHeight(5),
  },
  confirmtxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiRegular,
  },
  skipcontainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(150.5),
    marginTop: responsiveHeight(9),
    marginLeft: responsiveWidth(5),
    height: scale(49),
    backgroundColor: colors.color16,
    borderRadius: responsiveWidth(4.5),
  },
  numberttxt: {
    color: colors.color9,
    alignSelf: 'center',
    fontFamily: fontFamily.SatoshiRegular,
  },
  // thumbOffStyle: {
  //   backgroundColor: colors.color20,
  //   opacity: 0.5
  // },
  // thumbOff: {
  //   backgroundColor: colors.color20,
  //   opacity: 1
  // },
  // thumbOnStyle: {
  //   backgroundColor: colors.color20,
  // },
  cardContainer: {
    flexDirection: 'row',
    padding: responsiveWidth(3),
    borderRadius: responsiveWidth(7),
    borderColor: colors.color10,
    borderWidth: 0.5,
    width: scale(323),
    height: scale(132),
    alignSelf: 'center',
  },
  customstyle: {
    flexDirection: 'row',
    padding: responsiveWidth(3),
    borderRadius: responsiveWidth(7),
    borderColor: colors.color10,
    borderWidth: 0.5,
    width: scale(323),
    height: scale(132),
    alignSelf: 'center',
    backgroundColor: colors.color16,
    opacity: 0.5

  },
  cardImage: {
    width: scale(100),
    height: scale(116),
    borderRadius: responsiveWidth(4),
    resizeMode: 'contain',
    marginLeft: -responsiveWidth(1),
    marginRight: responsiveWidth(3.5),
    marginTop: -responsiveHeight(0.5)
  },
  Availabletxtview: {
    width: scale(88),
    height: scale(28),
    backgroundColor: colors.color33,
    borderRadius: responsiveWidth(50),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: responsiveHeight(1)
  },
  Available: {
    fontSize: fontSize.h2,
    fontWeight: '400',
    color: colors.color7,

    fontFamily: fontFamily.SatoshiMedium,
  },
  title: {
    fontSize: fontSize.h6,
    fontWeight: '700',
    color: colors.color4,
    marginBottom: responsiveHeight(0.5),
    fontFamily: fontFamily.SatoshiMedium,
  },
  customstyletitle: {
    fontSize: fontSize.h6,
    fontWeight: '700',
    color: colors.color4,
    marginBottom: responsiveHeight(0.5),
    fontFamily: fontFamily.SatoshiMedium,
    textDecorationLine: 'line-through'
  },
  description: {
    fontSize: fontSize.h2,
    color: colors.color10,
    fontFamily: fontFamily.SatoshiRegular,
    fontWeight: '400',
    marginTop: responsiveHeight(0.5)
  },
  customdescriptionstyle: {
    fontSize: fontSize.h2,
    color: colors.color10,
    fontFamily: fontFamily.SatoshiRegular,
    fontWeight: '400',
    marginTop: responsiveHeight(0.5),
    textDecorationLine: 'line-through'
  },
  headerchat: {
    height: responsiveHeight(11),
    backgroundColor: colors.color7,
    justifyContent: 'center',
  },
  // chatheaderImage: {
  //   width: scale(32),
  //   height: scale(32),
  //   resizeMode: 'contain',
  //   marginLeft: responsiveWidth(25),
  // },
  Threedot: {
    width: responsiveWidth(7),
    height: responsiveHeight(7),
    resizeMode: 'contain',
    alignSelf: 'flex-end',
  },
  // chatheaderview: {
  //   width: responsiveWidth(100),
  //   height: responsiveHeight(7),
  //   backgroundColor: colors.color7,
  //   alignItems: 'center',
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  jonetxt: {
    color: colors.color9,
    fontFamily: fontFamily.SatoshiVariable,
    fontSize: fontSize.h6,
    fontWeight: '700',
    marginRight: responsiveWidth(25),
  },
  arrowImage: {
    width: scale(10),
    height: scale(10),
    marginLeft: responsiveWidth(4),
    alignSelf: 'center',
  },
  arrowImage2: {
    width: scale(10),
    height: scale(10),
    marginLeft: -responsiveWidth(35),
    alignSelf: 'center',
    marginTop: -responsiveHeight(5),
  },

  downmodal: {
    backgroundColor: colors.color7,
    padding: responsiveHeight(2),
    borderTopLeftRadius: responsiveWidth(8),
    borderTopRightRadius: responsiveWidth(8),
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: scale(190),
  },
  modaltick: {
    width: scale(100),
    height: scale(100),
    resizeMode: 'contain'
  },
  QRmodal: {
    backgroundColor: colors.color7,
    padding: responsiveHeight(2),
    borderTopLeftRadius: responsiveWidth(8),
    borderTopRightRadius: responsiveWidth(8),
    borderBottomLeftRadius: 0,
    width: responsiveWidth(100),
    height: responsiveHeight(60),
    borderBottomRightRadius: 0,
    alignItems: 'center',
    position: 'absolute',
    bottom: -responsiveHeight(3),
    left: -responsiveWidth(5),
    right: 0,
  },
  modalText1: {
    color: colors.color9,
    fontSize: fontSize.h7,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    marginTop: responsiveHeight(4),
  },
  modalText2: {
    color: colors.color9,
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiLight,
    fontWeight: '400',
    opacity: 1,
  },
  errorimage: {
    width: scale(100),
    height: scale(100),
    resizeMode: 'contain',
  },
  yescontainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(148),
    height: scale(49),
    marginTop: responsiveHeight(4),
    // height: responsiveHeight(8.3),
    borderRadius: responsiveWidth(50),
    marginRight: responsiveWidth(3),
    backgroundColor: colors.color33,
  },
  nocontainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(148),
    height: scale(49),
    marginTop: responsiveHeight(4),
    // height: responsiveHeight(8.3),
    borderRadius: responsiveWidth(50),
    marginRight: responsiveWidth(3),
    backgroundColor: colors.color16,
  },
  chatmodal: {
    backgroundColor: colors.color7,
    padding: responsiveHeight(2),
    borderTopLeftRadius: responsiveWidth(8),
    borderTopRightRadius: responsiveWidth(8),
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: responsiveHeight(43),
  },
  intertcontenttxt: {
    color: '#343232',
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiBold,
    fontWeight: '400',

  },
  txttouchable: {
    width: scale(85),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.color31,
    height: scale(29),
    borderRadius: responsiveWidth(5),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(2),
    marginBottom: responsiveHeight(1),

  },
  // monthlytxt: {
  //   color: colors.color10,
  //   lineHeight: scale(20),
  //   fontFamily: fontFamily.SatoshiRegular,
  //   fontSize: fontSize.h2,
  //   fontWeight: '400',
  //   marginTop: responsiveHeight(0.9),
  //   marginLeft: responsiveWidth(75),
  //   opacity: 1,
  // },
  // interestview: {
  //   width: scale(320),
  //   alignSelf: 'center',
  //   // height: scale(109),
  //   padding: 10,
  //   flexDirection: 'row',
  //   // marginBottom:responsiveHeight(2),
  //   flexWrap: 'wrap',
  //   marginHorizontal: 10,

  //   marginTop: responsiveHeight(1),
  //   borderRadius: responsiveWidth(4),
  //   borderWidth: 0.5,
  //   borderColor: colors.color10,
  // },
  // profileimg: {
  //   width: scale(335),
  //   height: scale(420),
  //   borderRadius: responsiveWidth(9),
  //   alignSelf: 'center',
  // },
  // interstitself: {
  //   color: colors.color10,
  //   fontSize: fontSize.h2,
  //   fontFamily: fontFamily.SatoshiBold,
  //   fontWeight: '400',
  //   marginLeft: responsiveWidth(5.5),
  //   marginTop: responsiveHeight(1),
  // },
  container2: {
    flex: 1,
    padding: 16,
  },
  imageExplore: {
    width: scale(320),
    height: scale(610),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: -responsiveHeight(2.2),
  },
  mainview: {
    width: responsiveWidth(100), 
    flexGrow: 1,
    padding: responsiveWidth(8),
    marginTop: -responsiveHeight(1),
  },
  policyfirsttxt: {
    color: colors.color4,
    fontSize: fontSize.h6,
    fontFamily: fontFamily.SatoshiBold,
    fontWeight: '700',
    marginLeft: responsiveWidth(7.5),
    marginTop: responsiveHeight(3),
  },
  tagimage: {
    width: scale(24),
    height: scale(24),
    resizeMode: 'contain',
    marginTop: responsiveHeight(2)
  },
  copyimage: {
    width: scale(24),
    height: scale(24),
    resizeMode: 'contain',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(38)
  },
  tabmainview: {
    flexDirection: 'row',
    backgroundColor: colors.color7,
    elevation: 9,
    shadowColor: colors.color33,
    width: responsiveWidth(100),
    justifyContent: 'center',
    alignItems: "center",
    height: scale(86),
    borderTopWidth: 0.3,
    borderColor: colors.color10
  },
  infotxt: {
    fontSize: fontSize.h5,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700',
    color: colors.color33,
    marginLeft: responsiveWidth(5),
    marginTop: responsiveHeight(2),
    marginBottom: -responsiveHeight(1),
  },
  pickupsview: {
    width: scale(88),
    height: scale(28),
    flexDirection: 'row',
    borderColor: colors.color33,
    borderWidth: 1,
    borderRadius: responsiveWidth(50),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: responsiveHeight(1)
  },
  greenbasketImage: {
    width: scale(16),
    height: scale(16),
    resizeMode: 'contain',
    marginRight: responsiveWidth(1)
  },
  getdirectioncontainer: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(320),
    backgroundColor: colors.color7,
    borderWidth: 1,
    flexDirection: 'row',
    borderColor: colors.color33,
    height: scale(49),
    borderRadius: responsiveWidth(50),
    marginTop: responsiveHeight(6),

  },
  locationview:{
    width: scale(48),
    height: scale(48),
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:colors.color13,
    borderRadius:responsiveWidth(5),
    marginLeft:responsiveWidth(83),
    marginTop:-responsiveHeight(7.5)
  },
  helpview:{
    width: scale(48),
    height: scale(48),
  

    marginLeft:responsiveWidth(83),
    marginTop:-responsiveHeight(7.5)
  },
  removefrt: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: scale(320),
    backgroundColor: colors.color7,
    borderWidth: 1,
    flexDirection: 'row',
    borderColor: colors.color33,
    height: scale(49),
    borderRadius: responsiveWidth(50),
  },
  gettxt: {
    color: colors.color33,
    fontSize: fontSize.h6,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700'
  },
  helpmodal: {
    backgroundColor: colors.color7,
    padding: responsiveHeight(2),
    borderRadius: responsiveWidth(4),
    position: 'absolute',
    bottom: responsiveHeight(16),
    width: responsiveWidth(85),
    right: -responsiveWidth(1),
    height: responsiveHeight(17),
  },
  modaltitle: {
    color: colors.color4,
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '700'
  },
  DonationModal:{
    color: colors.color4,
  fontSize: fontSize.h6,
  fontFamily: fontFamily.SatoshiVariable,
  fontWeight: '700'
  },
  
  mapmainview: {
    width: scale(313),
    borderRadius: responsiveWidth(5),
    borderWidth: 1,
    borderColor: colors.color4,
    alignSelf: 'center',
    height: scale(250),
    marginTop: responsiveHeight(5),
    overflow: 'hidden'
  },
  plusbutton: {
    width: scale(48),
    height: scale(48),
    resizeMode: 'contain',
    marginLeft: responsiveWidth(81),
  },
  QRcode: {
    width: scale(150),
    height: scale(150),
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: responsiveHeight(4)
  },
  getview: {
    width: responsiveWidth(90),
    flexDirection: 'row',
    height: responsiveHeight(7)
  },
  qrsecondcode: {
    width: responsiveWidth(88),
    height:responsiveHeight(10.5),
    alignSelf:'center',
    alignItems: 'center'
  },
  qrmainview: {
    width: responsiveWidth(90),
    height: responsiveHeight(29),
    alignSelf: 'center',
    alignItems: 'center',
    borderRadius: responsiveWidth(4),
    borderWidth: 0.5,
    marginTop: responsiveHeight(4),
    borderColor: colors.color10
  },
  txtpartner: {
    color: colors.color4,
    fontSize: fontSize.h2,
    fontFamily: fontFamily.SatoshiVariable,
    fontWeight: '400',
  },
  partnertxtview: {
    width: responsiveWidth(90),
    alignSelf: 'center',
    alignItems: 'center',
   
    height: responsiveHeight(12),
  },
  createcheckview:{
    flexDirection:'row',
    marginLeft:responsiveWidth(4),
    marginTop:responsiveHeight(3),
  },
  createcheckview2:{
    flexDirection:'row',
    marginLeft:responsiveWidth(4),
    marginTop:responsiveHeight(3),
    width:scale(300),
    height:scale(48),
  },
  dropdownContainer: {
    // marginBottom: responsiveHeight(2),
  },
  Dropdown: {
    backgroundColor:colors.color7,
    borderRadius:responsiveWidth(3.2),
    borderColor: colors.color29,
    marginTop:responsiveHeight(0.1),
    width: responsiveWidth(90),
  },
  dropDownStyle: {
    backgroundColor:colors.color7,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    borderColor: colors.color29,
    width: responsiveWidth(90),
    marginLeft:responsiveWidth(5)
  },
  items: {
    justifyContent: 'flex-start',
    left: 10,
    top: 4,
    color:colors.color4,
  },
  dcontainer: {
    height: responsiveHeight(7),
    borderRadius: 5,
    width: responsiveWidth(90),
    marginTop: responsiveHeight(1),
  },
  loadingAnimation: {
    width: '40%',
    height: '18%',
    alignSelf: 'center',
  },
  loadingContainer: {
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
